// src/views/PackagesView.tsx
import { useEffect, useMemo, useState } from "react";
import { ArrowDownToLine, Boxes, Download, PackagePlus, RefreshCw, Search, Trash2 } from "lucide-react";
import { api } from "../api";
import { loadSettings } from "../settings";
import type { InstalledPackage, PackageGalleryItem } from "../types";
import { errorText } from "../lib/format";
import { Alert } from "../components/ui/alert";
import { Button } from "../components/ui/button";
import { Dialog } from "../components/ui/dialog";
import { confirmDialog, toast } from "../components/ui/feedback";
import { Field, Input } from "../components/ui/input";
import { Page } from "../components/ui/page";
import { Panel, PanelHeader } from "../components/ui/panel";
import { LoadingOverlay } from "../components/ui/spinner";
import { Table, TBody, TD, TH, THead, TR, TableEmpty } from "../components/ui/table";
import { Tag } from "../components/ui/tag";

/** 安装命令中的高风险提示片段：等宽字体强调真实执行的命令。 */
function CommandText({ children }: { children: string }) {
  return <span className="rounded-xs bg-muted px-1.5 py-0.5 font-mono text-[12px] text-ink">{children}</span>;
}

/**
 * 把来源规格缩到包身份，用于判断市场条目是否已安装。
 * npm：去掉 "npm:" 前缀后去掉末尾 "@version"；作用域包（@scope/pkg）的版本 @ 是最后一个 @。
 */
function baseName(source: string): string {
  if (source.startsWith("npm:")) {
    const rest = source.slice(4);
    const index = rest.lastIndexOf("@");
    return index > 0 ? rest.slice(0, index) : rest;
  }
  return source;
}

export default function PackagesView() {
  const [loading, setLoading] = useState(false);
  const [packages, setPackages] = useState<InstalledPackage[]>([]);
  const [installVisible, setInstallVisible] = useState(false);
  const [installLoading, setInstallLoading] = useState(false);
  const [installSource, setInstallSource] = useState("");
  const [removeActionId, setRemoveActionId] = useState("");
  const [updateLoading, setUpdateLoading] = useState(false);

  const [galleryVisible, setGalleryVisible] = useState(false);
  const [galleryLoading, setGalleryLoading] = useState(false);
  const [galleryItems, setGalleryItems] = useState<PackageGalleryItem[]>([]);
  const [gallerySearch, setGallerySearch] = useState("");
  const [galleryInstallingName, setGalleryInstallingName] = useState("");

  const sortedPackages = useMemo(
    () =>
      [...packages].sort((a, b) => {
        if (a.kind !== b.kind) return a.kind.localeCompare(b.kind);
        return a.source.localeCompare(b.source);
      }),
    [packages],
  );

  const npmCount = packages.filter((pkg) => pkg.kind === "npm").length;
  const gitCount = packages.filter((pkg) => pkg.kind === "git").length;
  const localCount = packages.filter((pkg) => pkg.kind === "local").length;

  const filteredGallery = useMemo(() => {
    const query = gallerySearch.trim().toLowerCase();
    if (!query) return galleryItems;
    return galleryItems.filter(
      (item) =>
        item.name.toLowerCase().includes(query) ||
        item.description.toLowerCase().includes(query) ||
        item.provider.toLowerCase().includes(query) ||
        item.types.toLowerCase().includes(query),
    );
  }, [galleryItems, gallerySearch]);

  const installedSources = useMemo(() => new Set(packages.map((pkg) => pkg.source)), [packages]);

  function isInstalled(item: PackageGalleryItem): boolean {
    const source = item.installCommand.replace(/^pi\s+install\s+/, "").trim();
    if (installedSources.has(source)) return true;
    const nameOnly = baseName(source);
    if (!nameOnly || nameOnly === source) return false;
    return [...installedSources].some((installed) => baseName(installed) === nameOnly);
  }

  async function loadPackages() {
    setLoading(true);
    try {
      setPackages(await api.listPackages(loadSettings().piPath || undefined));
    } catch (error) {
      toast.error(errorText(error));
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    void loadPackages();
  }, []);

  async function doInstall(source: string): Promise<boolean> {
    setInstallLoading(true);
    try {
      const result = await api.installPackage(source, loadSettings().piPath || undefined);
      if (result.success) {
        toast.success(`安装完成：${source}`);
        await loadPackages();
        return true;
      }
      toast.error(`安装失败：${result.output || "未知错误"}`);
      return false;
    } catch (error) {
      toast.error(errorText(error));
      return false;
    } finally {
      setInstallLoading(false);
    }
  }

  async function installFromInput() {
    const source = installSource.trim();
    if (!source) {
      toast.warning("请输入插件来源，如 npm:pi-mcp-adapter");
      return;
    }
    const confirmed = await confirmDialog({
      title: "安装插件",
      message: (
        <>
          将执行 <CommandText>{`pi install ${source}`}</CommandText> 安装插件。插件拥有完整系统访问权限，请确认来源可信。
        </>
      ),
      confirmText: "安装",
    });
    if (!confirmed) return;
    const ok = await doInstall(source);
    if (ok) {
      setInstallVisible(false);
      setInstallSource("");
    }
  }

  async function installFromGallery(item: PackageGalleryItem) {
    const command = item.installCommand || `pi install npm:${item.name}`;
    const source = command.replace(/^pi\s+install\s+/, "").trim();
    if (!source) {
      toast.warning("无法解析安装命令");
      return;
    }
    const confirmed = await confirmDialog({
      title: `安装 ${item.name}`,
      message: (
        <>
          将执行 <CommandText>{command}</CommandText> 安装插件。插件拥有完整系统访问权限，请确认来源可信。
        </>
      ),
      confirmText: "安装",
    });
    if (!confirmed) return;
    setGalleryInstallingName(item.name);
    const ok = await doInstall(source);
    setGalleryInstallingName("");
    if (ok) toast.success(`已安装 ${item.name}`);
  }

  async function removePackage(pkg: InstalledPackage) {
    const confirmed = await confirmDialog({
      title: "卸载插件",
      message: (
        <>
          将执行 <CommandText>{`pi remove ${pkg.source}`}</CommandText> 卸载该插件，是否继续？
        </>
      ),
      confirmText: "卸载",
    });
    if (!confirmed) return;
    setRemoveActionId(pkg.source);
    try {
      const result = await api.removePackage(pkg.source, loadSettings().piPath || undefined);
      if (result.success) {
        toast.success(`已卸载 ${pkg.source}`);
        await loadPackages();
      } else {
        toast.error(`卸载失败：${result.output || "未知错误"}`);
      }
    } catch (error) {
      toast.error(errorText(error));
    } finally {
      setRemoveActionId("");
    }
  }

  async function updateAllPackages() {
    const confirmed = await confirmDialog({
      title: "更新插件",
      message: (
        <>
          将执行 <CommandText>pi update --extensions</CommandText> 更新所有插件并同步 git 引用，可能需要较长时间。是否继续？
        </>
      ),
      confirmText: "更新",
    });
    if (!confirmed) return;
    setUpdateLoading(true);
    try {
      const result = await api.updatePackages(loadSettings().piPath || undefined);
      if (result.success) {
        toast.success("插件更新完成");
        await loadPackages();
      } else {
        toast.error(`更新失败：${result.output || "未知错误"}`);
      }
    } catch (error) {
      toast.error(errorText(error));
    } finally {
      setUpdateLoading(false);
    }
  }

  async function openGallery() {
    setGalleryVisible(true);
    setGallerySearch("");
    setGalleryItems([]);
    setGalleryLoading(true);
    try {
      const items = await api.searchPackages();
      setGalleryItems(items);
      if (!items.length) toast.info("pi.dev 暂无可用的插件");
    } catch (error) {
      toast.error(errorText(error));
    } finally {
      setGalleryLoading(false);
    }
  }

  async function searchGallery() {
    setGalleryLoading(true);
    try {
      const items = await api.searchPackages(gallerySearch || undefined);
      setGalleryItems(items);
      if (!items.length) toast.info("没有找到匹配的插件");
    } catch (error) {
      toast.error(errorText(error));
    } finally {
      setGalleryLoading(false);
    }
  }

  return (
    <Page
      title="插件管理"
      subtitle="管理 Pi 的已安装包，安装新插件，浏览 pi.dev 插件市场"
      loading={loading}
      actions={
        <>
          <Button icon={Boxes} onClick={() => void openGallery()}>
            浏览 pi.dev
          </Button>
          <Button icon={RefreshCw} onClick={() => void loadPackages()}>
            刷新
          </Button>
          <Button variant="primary" icon={PackagePlus} onClick={() => setInstallVisible(true)}>
            安装插件
          </Button>
        </>
      }
    >
      <Alert>
        已安装 <span className="font-mono">{packages.length}</span> 个插件
        <span className="ml-3.5">
          npm <strong>{npmCount}</strong>
        </span>
        <span className="ml-2.5">
          git <strong>{gitCount}</strong>
        </span>
        <span className="ml-2.5">
          local <strong>{localCount}</strong>
        </span>
      </Alert>

      <div className="mt-3.5 flex items-center gap-2.5">
        <Button size="sm" icon={Download} loading={updateLoading} onClick={() => void updateAllPackages()}>
          更新全部插件
        </Button>
        <span className="text-[12px] text-ink-2">运行 pi update --extensions 更新所有插件并同步 git 引用</span>
      </div>

      <Table className="mt-2">
        <THead>
          <TR className="hover:bg-transparent">
            <TH className="min-w-[280px]">来源</TH>
            <TH className="w-[100px]">类型</TH>
            <TH className="min-w-[200px]">范围 / 包名</TH>
            <TH className="w-[120px]" align="center">
              操作
            </TH>
          </TR>
        </THead>
        <TBody>
          {sortedPackages.length ? (
            sortedPackages.map((pkg) => (
              <TR key={pkg.source}>
                <TD>
                  <span className="font-mono">{pkg.source}</span>
                  {pkg.pinned ? (
                    <Tag className="ml-1.5" >
                      pinned
                    </Tag>
                  ) : null}
                </TD>
                <TD>
                  <Tag tone={pkg.kind === "git" ? "success" : "default"}>{pkg.kind}</Tag>
                </TD>
                <TD>
                  <span className="block max-w-[280px] truncate" title={pkg.scope}>
                    {pkg.scope}
                  </span>
                </TD>
                <TD align="center">
                  <Button
                    variant="linkDanger"
                    icon={Trash2}
                    loading={removeActionId === pkg.source}
                    onClick={() => void removePackage(pkg)}
                  >
                    卸载
                  </Button>
                </TD>
              </TR>
            ))
          ) : (
            <TableEmpty colSpan={4}>还没有安装插件</TableEmpty>
          )}
        </TBody>
      </Table>

      <Dialog
        open={installVisible}
        onOpenChange={setInstallVisible}
        title="安装插件"
        footer={
          <>
            <Button onClick={() => setInstallVisible(false)}>取消</Button>
            <Button variant="primary" icon={PackagePlus} loading={installLoading} onClick={() => void installFromInput()}>
              安装
            </Button>
          </>
        }
      >
        <div className="mb-[18px] flex items-center gap-3 rounded-md border border-line bg-muted p-[13px]">
          <div className="grid h-[34px] w-[34px] flex-none place-items-center rounded-md border border-line bg-panel text-accent">
            <PackagePlus size={21} />
          </div>
          <p className="m-0 text-[11px] leading-[1.55] text-ink-2">
            输入 <span className="font-mono">pi install</span> 的来源参数，支持 npm、git 和本地路径。插件拥有完整系统访问权限，请确认来源可信。
          </p>
        </div>
        <Field label="插件来源">
          <Input
            autoFocus
            value={installSource}
            placeholder="npm:pi-mcp-adapter"
            onChange={(event) => setInstallSource(event.target.value)}
            onKeyDown={(event) => {
              if (event.key === "Enter") void installFromInput();
            }}
          />
        </Field>
        <div className="text-[12px] leading-[1.6] text-ink-2">
          npm：<span className="font-mono">npm:pi-mcp-adapter</span>、<span className="font-mono">npm:@scope/pkg@1.0.0</span>
          <br />
          git：<span className="font-mono">git:github.com/user/repo</span>、
          <span className="font-mono">https://github.com/user/repo</span>
          <br />
          本地：<span className="font-mono">/absolute/path/to/package</span>、
          <span className="font-mono">./relative/path</span>
        </div>
      </Dialog>

      <Dialog
        open={galleryVisible}
        onOpenChange={setGalleryVisible}
        title="浏览 pi.dev 插件市场"
        width={960}
        footer={<Button onClick={() => setGalleryVisible(false)}>关闭</Button>}
      >
        <div className="toolbar mb-3.5">
          <Input
            value={gallerySearch}
            placeholder="搜索插件名称、描述、作者或类型"
            className="w-[300px] max-[600px]:w-full"
            onChange={(event) => setGallerySearch(event.target.value)}
            onKeyDown={(event) => {
              if (event.key === "Enter") void searchGallery();
            }}
          />
          <Button variant="primary" icon={Search} loading={galleryLoading} onClick={() => void searchGallery()}>
            搜索
          </Button>
          <span className="text-[12px] text-ink-2">
            {filteredGallery.length} / {galleryItems.length} 个
          </span>
        </div>

        <div className="relative grid max-h-[60vh] grid-cols-[repeat(auto-fill,minmax(300px,1fr))] gap-3.5 overflow-y-auto">
          <LoadingOverlay visible={galleryLoading} className="z-20" />
          {filteredGallery.map((item) => (
            <article
              key={item.name}
              className="flex flex-col gap-2 rounded-lg border border-line bg-panel p-4 transition-[border-color,box-shadow] hover:border-line-strong hover:shadow-[0_4px_12px_rgba(0,0,0,0.06)]"
            >
              <div className="flex items-start justify-between">
                <div className="text-accent">
                  <Boxes size={18} strokeWidth={1.7} />
                </div>
                <div className="flex flex-wrap justify-end gap-1">
                  {item.types
                    .split(" ")
                    .filter(Boolean)
                    .map((type) => (
                      <Tag key={type}>{type}</Tag>
                    ))}
                </div>
              </div>
              <div>
                <h2 className="m-0 text-body font-semibold text-ink">{item.name}</h2>
                <p className="mt-1 mb-0 line-clamp-2 overflow-hidden text-caption leading-[1.5] text-ink-2">
                  {item.description || "此插件没有提供描述。"}
                </p>
              </div>
              <div className="flex gap-2.5 text-micro text-ink-2">
                <span>{item.provider || "—"}</span>
                <span>{item.downloads}</span>
                <span>{item.updated}</span>
              </div>
              <div className="truncate rounded-sm bg-muted px-2 py-1.5 font-mono text-micro text-ink-2" title={item.installCommand}>
                {item.installCommand}
              </div>
              <div className="flex justify-end">
                <Button
                  size="sm"
                  variant="primary"
                  icon={ArrowDownToLine}
                  loading={galleryInstallingName === item.name}
                  disabled={isInstalled(item)}
                  onClick={() => void installFromGallery(item)}
                >
                  {isInstalled(item) ? "已安装" : "安装"}
                </Button>
              </div>
            </article>
          ))}

          {!galleryLoading && !filteredGallery.length ? (
            <Panel className="col-span-full grid place-items-center p-10 text-center">
              <div className="empty-state flex flex-col items-center justify-center">
                <strong className="text-control text-ink">没有匹配的插件</strong>
                <span className="mt-1.5 block">尝试更换搜索关键词。</span>
              </div>
            </Panel>
          ) : null}
        </div>
      </Dialog>
    </Page>
  );
}

// src/views/PackagesView.vue
<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { ArrowDownToLine, Boxes, Download, PackagePlus, RefreshCw, Search, Trash2 } from "@lucide/vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { api } from "../api";
import { loadSettings } from "../settings";
import type { InstalledPackage, PackageGalleryItem } from "../types";

const loading = ref(false);
const packages = ref<InstalledPackage[]>([]);
const installVisible = ref(false);
const installLoading = ref(false);
const installSource = ref("");
const removeActionId = ref("");
const updateLoading = ref(false);

const galleryVisible = ref(false);
const galleryLoading = ref(false);
const galleryItems = ref<PackageGalleryItem[]>([]);
const gallerySearch = ref("");
const galleryInstallingName = ref("");

const kindColors: Record<string, string> = {
  npm: "primary",
  git: "success",
  local: "info",
};

function errorText(error: unknown): string {
  return typeof error === "string" ? error : error instanceof Error ? error.message : String(error);
}

const sortedPackages = computed(() => {
  return [...packages.value].sort((a, b) => {
    if (a.kind !== b.kind) return a.kind.localeCompare(b.kind);
    return a.source.localeCompare(b.source);
  });
});

const npmCount = computed(() => packages.value.filter((p) => p.kind === "npm").length);
const gitCount = computed(() => packages.value.filter((p) => p.kind === "git").length);
const localCount = computed(() => packages.value.filter((p) => p.kind === "local").length);

async function loadPackages() {
  loading.value = true;
  try {
    packages.value = await api.listPackages(loadSettings().piPath || undefined);
  } catch (error) {
    ElMessage.error(errorText(error));
  } finally {
    loading.value = false;
  }
}

async function doInstall(source: string): Promise<boolean> {
  installLoading.value = true;
  try {
    const result = await api.installPackage(source, loadSettings().piPath || undefined);
    if (result.success) {
      ElMessage.success(`安装完成：${source}`);
      await loadPackages();
      return true;
    } else {
      ElMessage.error(`安装失败：${result.output || "未知错误"}`);
      return false;
    }
  } catch (error) {
    ElMessage.error(errorText(error));
    return false;
  } finally {
    installLoading.value = false;
  }
}

async function installFromInput() {
  const source = installSource.value.trim();
  if (!source) return ElMessage.warning("请输入插件来源，如 npm:pi-mcp-adapter");
  try {
    await ElMessageBox.confirm(
      `将执行 <span class="code">pi install ${source}</span> 安装插件。插件拥有完整系统访问权限，请确认来源可信。`,
      "安装插件",
      { type: "warning", confirmButtonText: "安装", cancelButtonText: "取消", dangerouslyUseHTMLString: true },
    );
  } catch {
    return;
  }
  const ok = await doInstall(source);
  if (ok) {
    installVisible.value = false;
    installSource.value = "";
  }
}

async function installFromGallery(item: PackageGalleryItem) {
  const command = item.installCommand || `pi install npm:${item.name}`;
  const source = command.replace(/^pi\s+install\s+/, "").trim();
  if (!source) return ElMessage.warning("无法解析安装命令");
  try {
    await ElMessageBox.confirm(
      `将执行 <span class="code">${command}</span> 安装插件。插件拥有完整系统访问权限，请确认来源可信。`,
      `安装 ${item.name}`,
      { type: "warning", confirmButtonText: "安装", cancelButtonText: "取消", dangerouslyUseHTMLString: true },
    );
  } catch {
    return;
  }
  galleryInstallingName.value = item.name;
  const ok = await doInstall(source);
  galleryInstallingName.value = "";
  if (ok) {
    ElMessage.success(`已安装 ${item.name}`);
  }
}

async function removePackage(pkg: InstalledPackage) {
  try {
    await ElMessageBox.confirm(
      `将执行 <span class="code">pi remove ${pkg.source}</span> 卸载该插件，是否继续？`,
      "卸载插件",
      { type: "warning", confirmButtonText: "卸载", cancelButtonText: "取消", dangerouslyUseHTMLString: true },
    );
    removeActionId.value = pkg.source;
    const result = await api.removePackage(pkg.source, loadSettings().piPath || undefined);
    if (result.success) {
      ElMessage.success(`已卸载 ${pkg.source}`);
      await loadPackages();
    } else {
      ElMessage.error(`卸载失败：${result.output || "未知错误"}`);
    }
  } catch (error) {
    if (error !== "cancel" && error !== "close") ElMessage.error(errorText(error));
  } finally {
    removeActionId.value = "";
  }
}

async function updateAllPackages() {
  try {
    await ElMessageBox.confirm(
      "将执行 <span class=\"code\">pi update --extensions</span> 更新所有插件并同步 git 引用，可能需要较长时间。是否继续？",
      "更新插件",
      { type: "warning", confirmButtonText: "更新", cancelButtonText: "取消", dangerouslyUseHTMLString: true },
    );
    updateLoading.value = true;
    const result = await api.updatePackages(loadSettings().piPath || undefined);
    if (result.success) {
      ElMessage.success("插件更新完成");
      await loadPackages();
    } else {
      ElMessage.error(`更新失败：${result.output || "未知错误"}`);
    }
  } catch (error) {
    if (error !== "cancel" && error !== "close") ElMessage.error(errorText(error));
  } finally {
    updateLoading.value = false;
  }
}

async function openGallery() {
  galleryVisible.value = true;
  gallerySearch.value = "";
  galleryItems.value = [];
  galleryLoading.value = true;
  try {
    galleryItems.value = await api.searchPackages();
    if (!galleryItems.value.length) ElMessage.info("pi.dev 暂无可用的插件");
  } catch (error) {
    ElMessage.error(errorText(error));
  } finally {
    galleryLoading.value = false;
  }
}

async function searchGallery() {
  galleryLoading.value = true;
  try {
    galleryItems.value = await api.searchPackages(gallerySearch.value || undefined);
    if (!galleryItems.value.length) ElMessage.info("没有找到匹配的插件");
  } catch (error) {
    ElMessage.error(errorText(error));
  } finally {
    galleryLoading.value = false;
  }
}

const filteredGallery = computed(() => {
  const query = gallerySearch.value.trim().toLowerCase();
  if (!query) return galleryItems.value;
  return galleryItems.value.filter(
    (item) =>
      item.name.toLowerCase().includes(query) ||
      item.description.toLowerCase().includes(query) ||
      item.provider.toLowerCase().includes(query) ||
      item.types.toLowerCase().includes(query),
  );
});

const installedSources = computed(() => new Set(packages.value.map((p) => p.source)));

function isInstalled(item: PackageGalleryItem): boolean {
  const source = item.installCommand.replace(/^pi\s+install\s+/, "").trim();
  if (installedSources.value.has(source)) return true;
  // Also check by npm name (version-pinned entries).
  const nameOnly = source.split("@")[0];
  return [...installedSources.value].some((s) => s.split("@")[0] === nameOnly);
}

onMounted(loadPackages);
</script>

<template>
  <section class="page packages-page" v-loading="loading">
    <header class="page-header">
      <div class="page-title"><h1>插件管理</h1><p>管理 Pi 的已安装包，安装新插件，浏览 pi.dev 插件市场</p></div>
      <div class="toolbar">
        <el-button :icon="Boxes" @click="openGallery">浏览 pi.dev</el-button>
        <el-button :icon="RefreshCw" @click="loadPackages">刷新</el-button>
        <el-button type="primary" :icon="PackagePlus" @click="installVisible = true">安装插件</el-button>
      </div>
    </header>

    <el-alert class="path-alert" type="info" :closable="false">
      <template #title>
        已安装 <span class="code">{{ packages.length }}</span> 个插件
        <span style="margin-left:14px">npm <strong>{{ npmCount }}</strong></span>
        <span style="margin-left:10px">git <strong>{{ gitCount }}</strong></span>
        <span style="margin-left:10px">local <strong>{{ localCount }}</strong></span>
      </template>
    </el-alert>

    <div class="packages-actions-bar">
      <el-button size="small" :icon="Download" :loading="updateLoading" @click="updateAllPackages">更新全部插件</el-button>
      <span class="muted" style="font-size:12px">运行 pi update --extensions 更新所有插件并同步 git 引用</span>
    </div>

    <el-table :data="sortedPackages" border empty-text="还没有安装插件" style="margin-top:8px">
      <el-table-column label="来源" min-width="280">
        <template #default="scope">
          <span class="code">{{ scope.row.source }}</span>
          <el-tag v-if="scope.row.pinned" size="small" effect="plain" style="margin-left:6px">pinned</el-tag>
        </template>
      </el-table-column>
      <el-table-column label="类型" width="100">
        <template #default="scope">
          <el-tag size="small" :type="(kindColors[scope.row.kind] as any) || 'info'">{{ scope.row.kind }}</el-tag>
        </template>
      </el-table-column>
      <el-table-column prop="scope" label="范围 / 包名" min-width="200" show-overflow-tooltip />
      <el-table-column label="操作" width="120" align="center">
        <template #default="scope">
          <el-button link type="danger" :icon="Trash2" :loading="removeActionId === scope.row.source" @click="removePackage(scope.row)">卸载</el-button>
        </template>
      </el-table-column>
    </el-table>

    <el-dialog v-model="installVisible" title="安装插件" width="560px" destroy-on-close>
      <div class="install-skill-intro">
        <div class="install-skill-icon"><PackagePlus :size="21" /></div>
        <p>输入 <span class="code">pi install</span> 的来源参数，支持 npm、git 和本地路径。插件拥有完整系统访问权限，请确认来源可信。</p>
      </div>
      <el-form label-position="top" @submit.prevent="installFromInput">
        <el-form-item label="插件来源">
          <el-input v-model="installSource" placeholder="npm:pi-mcp-adapter" clearable @keyup.enter="installFromInput" />
        </el-form-item>
        <div class="muted" style="font-size:12px;line-height:1.6">
          npm：<span class="code">npm:pi-mcp-adapter</span>、<span class="code">npm:@scope/pkg@1.0.0</span><br />
          git：<span class="code">git:github.com/user/repo</span>、<span class="code">https://github.com/user/repo</span><br />
          本地：<span class="code">/absolute/path/to/package</span>、<span class="code">./relative/path</span>
        </div>
      </el-form>
      <template #footer>
        <el-button @click="installVisible = false">取消</el-button>
        <el-button type="primary" :loading="installLoading" :icon="PackagePlus" @click="installFromInput">安装</el-button>
      </template>
    </el-dialog>

    <el-dialog v-model="galleryVisible" title="浏览 pi.dev 插件市场" width="960px" destroy-on-close>
      <div class="toolbar gallery-toolbar">
        <el-input v-model="gallerySearch" style="width:300px" placeholder="搜索插件名称、描述、作者或类型" clearable @keyup.enter="searchGallery" />
        <el-button type="primary" :icon="Search" :loading="galleryLoading" @click="searchGallery">搜索</el-button>
        <span class="muted" style="font-size:12px">{{ filteredGallery.length }} / {{ galleryItems.length }} 个</span>
      </div>
      <div v-loading="galleryLoading" class="gallery-grid">
        <article v-for="item in filteredGallery" :key="item.name" class="gallery-card">
          <div class="gallery-card-top">
            <div class="gallery-mark"><Boxes :size="18" :stroke-width="1.7" /></div>
            <div class="gallery-types">
              <el-tag v-for="t in item.types.split(' ').filter(Boolean)" :key="t" size="small" effect="plain">{{ t }}</el-tag>
            </div>
          </div>
          <div class="gallery-copy">
            <h2>{{ item.name }}</h2>
            <p>{{ item.description || "此插件没有提供描述。" }}</p>
          </div>
          <div class="gallery-meta">
            <span>{{ item.provider || "—" }}</span>
            <span>{{ item.downloads }}</span>
            <span>{{ item.updated }}</span>
          </div>
          <div class="gallery-install-box code" :title="item.installCommand">{{ item.installCommand }}</div>
          <div class="gallery-actions">
            <el-button
              size="small"
              type="primary"
              :icon="ArrowDownToLine"
              :loading="galleryInstallingName === item.name"
              :disabled="isInstalled(item)"
              @click="installFromGallery(item)"
            >{{ isInstalled(item) ? "已安装" : "安装" }}</el-button>
          </div>
        </article>
        <div v-if="!galleryLoading && !filteredGallery.length" class="panel gallery-empty">
          <div class="empty-state"><strong>没有匹配的插件</strong><span>尝试更换搜索关键词。</span></div>
        </div>
      </div>
      <template #footer><el-button @click="galleryVisible = false">关闭</el-button></template>
    </el-dialog>
  </section>
</template>

<style scoped>
.packages-actions-bar {
  display: flex;
  align-items: center;
  gap: 10px;
  margin-top: 14px;
}
.gallery-toolbar {
  margin-bottom: 14px;
}
.gallery-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 14px;
  max-height: 60vh;
  overflow-y: auto;
}
.gallery-card {
  display: flex;
  flex-direction: column;
  gap: 8px;
  padding: 16px;
  border: 1px solid var(--el-border-color-light);
  border-radius: 10px;
  background: var(--el-bg-color);
  transition: border-color .2s, box-shadow .2s;
}
.gallery-card:hover {
  border-color: var(--el-color-primary-light-5);
  box-shadow: 0 4px 12px rgba(0, 0, 0, .06);
}
.gallery-card-top {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
}
.gallery-mark {
  color: var(--el-color-primary);
}
.gallery-types {
  display: flex;
  gap: 4px;
  flex-wrap: wrap;
  justify-content: flex-end;
}
.gallery-copy h2 {
  font-size: 15px;
  font-weight: 600;
  margin: 0;
}
.gallery-copy p {
  font-size: 13px;
  color: var(--el-text-color-secondary);
  margin: 4px 0 0;
  line-height: 1.5;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
.gallery-meta {
  display: flex;
  gap: 10px;
  font-size: 12px;
  color: var(--el-text-color-secondary);
}
.gallery-install-box {
  font-size: 12px;
  padding: 6px 8px;
  border-radius: 6px;
  background: var(--el-fill-color-light);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.gallery-actions {
  display: flex;
  justify-content: flex-end;
}
.gallery-empty {
  grid-column: 1 / -1;
  padding: 40px;
  text-align: center;
}
</style>
