// src/views/SessionsView.tsx
import { useEffect, useMemo, useState } from "react";
import { Archive, ArrowDownToLine, MoreHorizontal, Pencil, Play, RefreshCw, Search, Trash2 } from "lucide-react";
import { api } from "../api";
import { loadSettings } from "../settings";
import type { DisplayEntry, SessionDetail, SessionSummary } from "../types";
import { errorText, formatShortTokens, formatTime } from "../lib/format";
import { cn } from "../lib/utils";
import { Button } from "../components/ui/button";
import { Checkbox } from "../components/ui/checkbox";
import { Collapsible } from "../components/ui/collapsible";
import { Dropdown, DropdownItem, DropdownSeparator } from "../components/ui/dropdown";
import { confirmDialog, promptDialog, toast } from "../components/ui/feedback";
import { Input } from "../components/ui/input";
import { Page } from "../components/ui/page";
import { Panel, PanelHeader } from "../components/ui/panel";
import { LoadingOverlay } from "../components/ui/spinner";

/** 会话气泡：按角色切换底色与对齐，工具结果用等宽字体、历史分支降低透明度。 */
function messageClasses(entry: DisplayEntry): string {
  const role = entry.role || entry.entryType;
  return cn(
    "mb-3.5 max-w-[min(88%,760px)]",
    role === "user" && "ml-auto",
    !entry.active && "opacity-50",
  );
}

export default function SessionsView() {
  const [loading, setLoading] = useState(false);
  const [detailLoading, setDetailLoading] = useState(false);
  const [sessions, setSessions] = useState<SessionSummary[]>([]);
  const [selectedPath, setSelectedPath] = useState("");
  const [detail, setDetail] = useState<SessionDetail | null>(null);
  const [keyword, setKeyword] = useState("");
  const [activeOnly, setActiveOnly] = useState(true);

  const filteredSessions = useMemo(() => {
    const query = keyword.trim().toLowerCase();
    if (!query) return sessions;
    return sessions.filter((session) =>
      [session.name, session.id, session.cwd, session.firstMessage, session.model, session.provider].some((value) =>
        value?.toLowerCase().includes(query),
      ),
    );
  }, [keyword, sessions]);

  const displayEntries = useMemo(() => {
    if (!detail) return [];
    return activeOnly ? detail.entries.filter((entry) => entry.active) : detail.entries;
  }, [activeOnly, detail]);

  async function selectSession(session: SessionSummary) {
    setSelectedPath(session.path);
    setDetailLoading(true);
    try {
      setDetail(await api.getSessionDetail(session.path));
    } catch (error) {
      toast.error(errorText(error));
    } finally {
      setDetailLoading(false);
    }
  }

  async function loadSessions(keepSelection = true) {
    setLoading(true);
    try {
      const previous = keepSelection ? selectedPath : "";
      const list = await api.listSessions(loadSettings().sessionsDir || undefined);
      setSessions(list);
      if (previous && list.some((session) => session.path === previous)) {
        await selectSession(list.find((session) => session.path === previous)!);
      } else if (list.length) {
        await selectSession(list[0]);
      } else {
        setSelectedPath("");
        setDetail(null);
      }
    } catch (error) {
      toast.error(errorText(error));
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    void loadSessions(false);
  }, []);

  async function continueSession() {
    if (!detail) return;
    try {
      const settings = loadSettings();
      await api.continueSession(detail.summary.id, detail.summary.cwd, settings.piPath || undefined);
      toast.success("已在外部终端打开 Pi");
    } catch (error) {
      toast.error(errorText(error));
    }
  }

  async function renameSession() {
    if (!detail) return;
    const name = await promptDialog({
      title: "重命名",
      message: "请输入新的会话名称",
      defaultValue: detail.summary.name || "",
      confirmText: "确定",
      validate: (value) => (value.trim() ? null : "名称不能为空"),
    });
    if (name === null) return;
    try {
      await api.renameSession(detail.summary.path, name);
      await loadSessions(true);
      toast.success("会话名称已更新");
    } catch (error) {
      toast.error(errorText(error));
    }
  }

  async function deleteSession() {
    if (!detail) return;
    const confirmed = await confirmDialog({
      title: "删除会话",
      message: "将永久删除此 Session JSONL 文件，是否继续？",
      confirmText: "删除",
    });
    if (!confirmed) return;
    try {
      await api.deleteSession(detail.summary.path);
      setSelectedPath("");
      await loadSessions(false);
      toast.success("会话已删除");
    } catch (error) {
      toast.error(errorText(error));
    }
  }

  async function exportSession() {
    if (!detail) return;
    try {
      const result = await api.exportSession(detail.summary.path, loadSettings().piPath || undefined);
      if (result.success) toast.success(`已导出到 ${result.output}`);
      else toast.error(result.output || "导出失败");
    } catch (error) {
      toast.error(errorText(error));
    }
  }

  return (
    <Page
      title="对话管理"
      subtitle="浏览、管理并继续 Pi 历史 Session"
      actions={
        <Button icon={RefreshCw} loading={loading} onClick={() => void loadSessions(true)}>
          刷新
        </Button>
      }
    >
      <div className="grid min-h-[calc(100vh_-_169px)] grid-cols-[minmax(340px,36%)_minmax(0,1fr)] gap-4 max-[900px]:min-h-0 max-[900px]:grid-cols-1">
        <Panel>
          <PanelHeader>
            <div className="relative w-full">
              <Search size={13} className="pointer-events-none absolute top-1/2 left-3 -translate-y-1/2 text-ink-3" />
              <Input
                value={keyword}
                placeholder="搜索名称、ID、项目或模型"
                className="pl-8"
                onChange={(event) => setKeyword(event.target.value)}
              />
            </div>
            <span className="text-[12px] whitespace-nowrap text-ink-2">{filteredSessions.length} 个</span>
          </PanelHeader>
          <div className="relative">
            <LoadingOverlay visible={loading} />
            <div className="max-h-[calc(100vh_-_245px)] overflow-auto max-[900px]:max-h-[360px]">
              {filteredSessions.length ? (
                filteredSessions.map((session) => (
                  <article
                    key={session.path}
                    onClick={() => void selectSession(session)}
                    className={cn(
                      "relative cursor-pointer border-b border-line px-4 py-3.5 transition-colors last:border-b-0",
                      "hover:bg-hover active:bg-active",
                      selectedPath === session.path && "bg-accent-soft",
                    )}
                  >
                    {selectedPath === session.path ? (
                      <span className="absolute top-0 bottom-0 left-0 w-0.5 bg-accent" />
                    ) : null}
                    <div className="flex items-baseline justify-between gap-2.5 text-caption">
                      <strong className="overflow-hidden text-control font-semibold text-ellipsis whitespace-nowrap text-ink">
                        {session.name || session.firstMessage || "未命名会话"}
                      </strong>
                      <span className="flex-none text-[10px] text-ink-3">{formatTime(session.modifiedAt)}</span>
                    </div>
                    <div className="my-[6px] h-8 overflow-hidden text-[11px] leading-4 text-ink-2">
                      {session.firstMessage || session.cwd}
                    </div>
                    <div className="flex justify-between gap-2.5 text-[10px] tabular-nums text-ink-3">
                      <span>
                        {session.provider && session.model ? `${session.provider}/${session.model}` : session.id}
                      </span>
                      <span>
                        {session.messageCount} 条 · {formatShortTokens(session.totalTokens)}
                      </span>
                    </div>
                  </article>
                ))
              ) : (
                <div className="empty-state">没有找到 Session</div>
              )}
            </div>
          </div>
        </Panel>

        <Panel>
          <LoadingOverlay visible={detailLoading} className="z-20" />
          {detail ? (
            <>
              <PanelHeader>
                <div className="min-w-0">
                  <h2 className="truncate">
                    {detail.summary.name || detail.summary.firstMessage || "未命名会话"}
                  </h2>
                  <div className="mt-[5px] font-mono text-[11px] text-ink-2 select-text">
                    pi --session {detail.summary.id}
                  </div>
                </div>
                <div className="toolbar">
                  <Button size="sm" variant="primary" icon={Play} onClick={() => void continueSession()}>
                    继续对话
                  </Button>
                  <Dropdown
                    trigger={
                      <Button size="sm" icon={MoreHorizontal} aria-label="更多操作" />
                    }
                  >
                    <DropdownItem icon={Pencil} onSelect={() => void renameSession()}>
                      重命名
                    </DropdownItem>
                    <DropdownItem icon={ArrowDownToLine} onSelect={() => void exportSession()}>
                      导出 HTML
                    </DropdownItem>
                    <DropdownSeparator />
                    <DropdownItem icon={Trash2} danger onSelect={() => void deleteSession()}>
                      删除
                    </DropdownItem>
                  </Dropdown>
                </div>
              </PanelHeader>

              <div className="border-b border-line bg-muted px-4 py-3 text-[11px] text-ink-2">
                <div className="flex flex-wrap justify-between gap-3.5">
                  <span className="font-mono" title={detail.summary.cwd}>
                    {detail.summary.cwd}
                  </span>
                  <span>
                    {detail.summary.messageCount} 条消息 · {formatShortTokens(detail.summary.totalTokens)} tokens · $
                    {detail.summary.totalCost.toFixed(4)}
                  </span>
                </div>
                <Checkbox checked={activeOnly} onCheckedChange={setActiveOnly} className="mt-2">
                  仅显示当前活动分支
                </Checkbox>
              </div>

              <div className="h-[calc(100vh_-_241px)] overflow-auto bg-panel p-[22px] max-[900px]:h-auto max-[900px]:max-h-[600px] max-[600px]:p-3.5">
                {displayEntries.length ? (
                  displayEntries.map((entry) => {
                    const role = entry.role || entry.entryType;
                    const isUser = role === "user";
                    return (
                      <article key={entry.id} className={messageClasses(entry)}>
                        <div
                          className={cn(
                            "relative rounded-lg border border-line bg-panel px-[15px] py-3 shadow-sm",
                            isUser && "border-accent bg-accent text-inverse",
                            role === "assistant" && "rounded-bl-xs",
                            (role === "toolResult" || role === "bashExecution") && "bg-muted font-mono",
                            entry.isError && "border-[#ef9a9a] bg-[#fff5f5]",
                          )}
                        >
                          {isUser ? null : (
                            <div className="absolute top-3 -left-2.5 grid h-5 w-5 place-items-center rounded-sm border border-line bg-panel text-accent shadow-sm">
                              <Archive size={13} />
                            </div>
                          )}
                          <div
                            className={cn(
                              "mb-1.5 flex items-center justify-between gap-3 text-[10px]",
                              isUser ? "text-[rgba(255,255,255,0.84)]" : "text-ink-3",
                            )}
                          >
                            <strong className="font-semibold">
                              {entry.title}
                              {entry.toolName ? ` · ${entry.toolName}` : ""}
                            </strong>
                            <span>
                              {formatTime(entry.timestamp)}
                              {entry.active ? "" : " · 历史分支"}
                            </span>
                          </div>
                          {entry.text ? (
                            <p
                              className={cn(
                                "m-0 text-caption leading-[1.65] break-words whitespace-pre-wrap",
                                isUser ? "text-[rgba(255,255,255,0.84)]" : "text-ink",
                              )}
                            >
                              {entry.text}
                            </p>
                          ) : null}
                          {entry.thinking ? (
                            <Collapsible title="查看思考内容" className="mt-2">
                              <p className="m-0 text-caption leading-[1.65] break-words whitespace-pre-wrap text-ink-2">
                                {entry.thinking}
                              </p>
                            </Collapsible>
                          ) : null}
                          {entry.provider && entry.model ? (
                            <div className="mt-2 font-mono text-[10px] text-ink-2">
                              {entry.provider}/{entry.model}
                            </div>
                          ) : null}
                        </div>
                      </article>
                    );
                  })
                ) : (
                  <div className="empty-state">此 Session 没有可显示的记录</div>
                )}
              </div>
            </>
          ) : (
            <div className="empty-state">选择一个 Session 查看对话</div>
          )}
        </Panel>
      </div>
    </Page>
  );
}

// src/views/SessionsView.vue
<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { Archive, ArrowDownToLine, MoreHorizontal, Pencil, Play, RefreshCw, Search, Trash2 } from "@lucide/vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { api } from "../api";
import { loadSettings } from "../settings";
import type { DisplayEntry, SessionDetail, SessionSummary } from "../types";

const loading = ref(false);
const detailLoading = ref(false);
const sessions = ref<SessionSummary[]>([]);
const selectedPath = ref("");
const detail = ref<SessionDetail | null>(null);
const keyword = ref("");
const activeOnly = ref(true);

const filteredSessions = computed(() => {
  const query = keyword.value.trim().toLowerCase();
  if (!query) return sessions.value;
  return sessions.value.filter((session) => [session.name, session.id, session.cwd, session.firstMessage, session.model, session.provider]
    .some((value) => value?.toLowerCase().includes(query)));
});

const displayEntries = computed(() => {
  if (!detail.value) return [];
  return activeOnly.value ? detail.value.entries.filter((entry) => entry.active) : detail.value.entries;
});

function errorText(error: unknown): string {
  return typeof error === "string" ? error : error instanceof Error ? error.message : String(error);
}

function formatTime(value: string): string {
  if (!value) return "-";
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }).format(date);
}

function formatTokens(value: number): string {
  return value >= 1_000_000 ? `${(value / 1_000_000).toFixed(1)}M` : value >= 1_000 ? `${(value / 1_000).toFixed(1)}K` : String(value);
}

async function loadSessions(keepSelection = true) {
  loading.value = true;
  try {
    const previous = keepSelection ? selectedPath.value : "";
    sessions.value = await api.listSessions(loadSettings().sessionsDir || undefined);
    if (previous && sessions.value.some((session) => session.path === previous)) {
      await selectSession(sessions.value.find((session) => session.path === previous)!);
    } else if (sessions.value.length) {
      await selectSession(sessions.value[0]);
    } else {
      selectedPath.value = "";
      detail.value = null;
    }
  } catch (error) {
    ElMessage.error(errorText(error));
  } finally {
    loading.value = false;
  }
}

async function selectSession(session: SessionSummary) {
  selectedPath.value = session.path;
  detailLoading.value = true;
  try {
    detail.value = await api.getSessionDetail(session.path);
  } catch (error) {
    ElMessage.error(errorText(error));
  } finally {
    detailLoading.value = false;
  }
}

async function continueSession() {
  if (!detail.value) return;
  try {
    const settings = loadSettings();
    await api.continueSession(detail.value.summary.id, detail.value.summary.cwd, settings.piPath || undefined);
    ElMessage.success("已在外部终端打开 Pi");
  } catch (error) {
    ElMessage.error(errorText(error));
  }
}

async function renameSession() {
  if (!detail.value) return;
  try {
    const result = await ElMessageBox.prompt("请输入新的会话名称", "重命名", {
      inputValue: detail.value.summary.name || "",
      inputValidator: (value) => Boolean(value.trim()) || "名称不能为空",
    });
    await api.renameSession(detail.value.summary.path, result.value);
    await loadSessions(true);
    ElMessage.success("会话名称已更新");
  } catch (error) {
    if (error !== "cancel" && error !== "close") ElMessage.error(errorText(error));
  }
}

async function deleteSession() {
  if (!detail.value) return;
  try {
    await ElMessageBox.confirm("将永久删除此 Session JSONL 文件，是否继续？", "删除会话", { type: "warning", confirmButtonText: "删除" });
    await api.deleteSession(detail.value.summary.path);
    selectedPath.value = "";
    await loadSessions(false);
    ElMessage.success("会话已删除");
  } catch (error) {
    if (error !== "cancel" && error !== "close") ElMessage.error(errorText(error));
  }
}

async function exportSession() {
  if (!detail.value) return;
  try {
    const result = await api.exportSession(detail.value.summary.path, loadSettings().piPath || undefined);
    if (result.success) ElMessage.success(`已导出到 ${result.output}`);
    else ElMessage.error(result.output || "导出失败");
  } catch (error) {
    ElMessage.error(errorText(error));
  }
}

function messageClass(entry: DisplayEntry): string[] {
  return ["message", entry.role || entry.entryType, entry.active ? "" : "inactive-branch"];
}

onMounted(() => loadSessions(false));
</script>

<template>
  <section class="page">
    <header class="page-header">
      <div class="page-title"><h1>对话管理</h1><p>浏览、管理并继续 Pi 历史 Session</p></div>
      <div class="toolbar"><el-button :icon="RefreshCw" :loading="loading" @click="loadSessions(true)">刷新</el-button></div>
    </header>

    <div class="session-grid">
      <div class="panel">
        <div class="panel-header">
          <el-input v-model="keyword" :prefix-icon="Search" clearable placeholder="搜索名称、ID、项目或模型" />
          <span class="muted" style="white-space:nowrap;font-size:12px">{{ filteredSessions.length }} 个</span>
        </div>
        <div class="session-list" v-loading="loading">
          <div v-if="!filteredSessions.length" class="empty-state">没有找到 Session</div>
          <article v-for="session in filteredSessions" :key="session.path" class="session-item" :class="{ active: selectedPath === session.path }" @click="selectSession(session)">
            <div class="session-item-title"><strong>{{ session.name || session.firstMessage || "未命名会话" }}</strong><span class="muted">{{ formatTime(session.modifiedAt) }}</span></div>
            <div class="session-item-text">{{ session.firstMessage || session.cwd }}</div>
            <div class="session-item-meta"><span>{{ session.provider && session.model ? `${session.provider}/${session.model}` : session.id }}</span><span>{{ session.messageCount }} 条 · {{ formatTokens(session.totalTokens) }}</span></div>
          </article>
        </div>
      </div>

      <div class="panel" v-loading="detailLoading">
        <template v-if="detail">
          <div class="panel-header">
            <div style="min-width:0"><h2 style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap">{{ detail.summary.name || detail.summary.firstMessage || "未命名会话" }}</h2><div class="muted code" style="margin-top:5px;font-size:11px;user-select:text">pi --session {{ detail.summary.id }}</div></div>
            <div class="toolbar">
              <el-button size="small" type="primary" :icon="Play" @click="continueSession">继续对话</el-button>
              <el-dropdown trigger="click">
                <el-button size="small" :icon="MoreHorizontal" aria-label="更多操作"></el-button>
                <template #dropdown><el-dropdown-menu><el-dropdown-item :icon="Pencil" @click="renameSession">重命名</el-dropdown-item><el-dropdown-item :icon="ArrowDownToLine" @click="exportSession">导出 HTML</el-dropdown-item><el-dropdown-item :icon="Trash2" divided @click="deleteSession">删除</el-dropdown-item></el-dropdown-menu></template>
              </el-dropdown>
            </div>
          </div>
          <div class="detail-meta">
            <div style="display:flex;justify-content:space-between;gap:14px;flex-wrap:wrap"><span class="code" :title="detail.summary.cwd">{{ detail.summary.cwd }}</span><span>{{ detail.summary.messageCount }} 条消息 · {{ formatTokens(detail.summary.totalTokens) }} tokens · ${{ detail.summary.totalCost.toFixed(4) }}</span></div>
            <el-checkbox v-model="activeOnly" size="small" style="margin-top:8px">仅显示当前活动分支</el-checkbox>
          </div>
          <div class="conversation">
            <article v-for="entry in displayEntries" :key="entry.id" :class="messageClass(entry)">
              <div class="message-card" :style="entry.isError ? 'border-color:#ef9a9a;background:#fff5f5' : ''"><div class="message-accent"><Archive :size="13" /></div>
                <div class="message-head"><strong>{{ entry.title }}<span v-if="entry.toolName"> · {{ entry.toolName }}</span></strong><span>{{ formatTime(entry.timestamp) }}<template v-if="!entry.active"> · 历史分支</template></span></div>
                <p v-if="entry.text" class="message-text">{{ entry.text }}</p>
                <el-collapse v-if="entry.thinking" style="margin-top:8px"><el-collapse-item title="查看思考内容"><p class="message-text muted">{{ entry.thinking }}</p></el-collapse-item></el-collapse>
                <div v-if="entry.provider && entry.model" class="muted code" style="margin-top:8px;font-size:10px">{{ entry.provider }}/{{ entry.model }}</div>
              </div>
            </article>
            <div v-if="!displayEntries.length" class="empty-state">此 Session 没有可显示的记录</div>
          </div>
        </template>
        <div v-else class="empty-state">选择一个 Session 查看对话</div>
      </div>
    </div>
  </section>
</template>
